.PHONY: clean All

All:
	@echo "----------Building project:[ Prj2 - Debug ]----------"
	@cd "Prj2" && $(MAKE) -f  "Prj2.mk"
clean:
	@echo "----------Cleaning project:[ Prj2 - Debug ]----------"
	@cd "Prj2" && $(MAKE) -f  "Prj2.mk" clean
